apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-jenkin-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-jenkin-k8s-app
  template:
    metadata:
      labels:
        app: nestjs-jenkin-k8s-app
    spec:
      containers:
        - name: nestjs
          image: ytthpch/nestjs-jenkin-k8s:1.3
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
          env:
            - name: APP_VERSION
              value: "1.2"
