apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-jenkin-k8s-app
spec:
  replicas: 1

  selector:
    matchLabels:
      app: nestjs-jenkin-k8s-app

  template:
    metadata:
      labels:
        app: nestjs-jenkin-k8s-app

    spec:
      containers:
        - name: nestjs
          image: ytthpch/nestjs-jenkin-k8s:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: nestjs-jenkin-k8s-env

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"